# Generated by Django 4.1.7 on 2023-04-17 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='photos/profile_pic/default.jpg', upload_to='photos/profile_pic'),
        ),
    ]
